name: hooklint
description: Format and analyze code using pre-commit.
version: 0.1.2
homepage: https://github.com/anandzhang/hooklint_dart
repository: https://github.com/anandzhang/hooklint_dart
documentation: https://github.com/anandzhang/hooklint_dart/blob/main/README.md
issue_tracker: https://github.com/anandzhang/hooklint_dart/issues

executables:
  hooklint:

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
