#!/bin/bash

# only handle Added,Copied,Modified files
STAGED_FILES="$(git diff --name-only --cached --diff-filter=ACM -- '*.dart')"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

# auto fix linter rules
for FILE in $STAGED_FILES; do
  # dart fix only one file
  dart fix --apply "$FILE"
done

dart format $STAGED_FILES
git add $STAGED_FILES
dart analyze $STAGED_FILES

exit $?
